/* ============================================================
   build.mjs  ::  static site build for thebharath.co
   Transforms the JSX sources (which rely on global React /
   ReactDOM) into a single minified bundle.js, and minifies the
   stylesheet, emitting deploy-ready artifacts to the repo root.
   The browser never ships an in-page transpiler. No framework,
   fully static, GitHub Pages friendly (served from root).
   ============================================================ */
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";

// Plain JS sources are concatenated verbatim (already valid).
const JS_SOURCES = ["src/content.js"];

// JSX sources, in the original prototype's <script> load order.
// They share a single global lexical scope (e.g. `const {useState}=React`
// declared in gta_components is read bare in the other files), so they
// must NOT be wrapped per-file. esbuild's transform mode keeps top-level
// names, so plain concatenation preserves that contract.
const JSX_SOURCES = [
  "src/gta_components.jsx",
  "src/gta_hero.jsx",
  "src/gta_skills_exp.jsx",
  "src/gta_projects.jsx",
  "src/gta_trophy_contact.jsx",
  "src/gta_app.jsx",
];

async function transformJsx(file) {
  const result = await build({
    entryPoints: [file],
    write: false,
    bundle: false,
    minify: true,
    jsx: "transform",
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
    loader: { ".jsx": "jsx" },
  });
  return result.outputFiles[0].text;
}

async function run() {
  let bundle =
    "/* generated by build.mjs from src/ - do not edit directly */\n";
  for (const f of JS_SOURCES) bundle += (await readFile(f, "utf8")) + "\n";
  for (const f of JSX_SOURCES) bundle += (await transformJsx(f)) + "\n";
  await writeFile("bundle.js", bundle);

  const css = await build({
    entryPoints: ["src/gta.css"],
    write: false,
    minify: true,
    loader: { ".css": "css" },
  });
  await writeFile("gta.css", css.outputFiles[0].text);

  console.log("Built: gta.css, bundle.js");
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
